import type { Metadata } from "next";
import { Montserrat, Judson } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { CartProvider } from "@/components/cart/cart-context";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";

const montserrat = Montserrat({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const judson = Judson({
  variable: "--font-serif",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Misjudged Apparel",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.ico",                   // browser tab
    shortcut: "/logo.ico",               // quick access
    apple: "/logo.ico",         // iOS icon
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = (await cookies()).get("cartId")?.value;
  const cart = getCart(cartId)
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${judson.variable} font-sans antialiased`}
      >
        <CartProvider cartPromise={cart}>
        <Navbar />
        {children}
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
